# When `preview-build` start. Leave a message on the PR
#
# 🚨🚨🚨 Important 🚨🚨🚨
# Never do any `checkout` or `npm install` action!
# `pull_request_target` will enable PR to access the secrets!

name: Visual-diff Regression Start

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  preview-start:
    permissions:
      issues: write  # for actions-cool/maintain-one-comment to modify or create issue comments
      pull-requests: write  # for actions-cool/maintain-one-comment to modify or create PR comments
    name: start visual diff regression info
    runs-on: ubuntu-latest
    steps:
      - name: update status comment
        uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # todo: replace link with ci job visual-diff regression build url
          body: |
            [![Prepare visual-diff regression](https://user-images.githubusercontent.com/5378891/72351368-2c979e00-371b-11ea-9652-eb4e825d745e.gif)](https://preview-${{ github.event.workflow_run.id }}-ant-design.surge.sh)
            <!-- VISUAL_DIFF_REGRESSION_HOOK -->
          body-include: '<!-- VISUAL_DIFF_REGRESSION_HOOK -->'
